[package]
name = "files"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.218", features = ["derive"] }
errors = { path = "../errors" }
thread_pool = { path = "../thread_pool" }
net = { path = "../net" }

